---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: pages
  label: Pages
  create: all
  match: "**/*"
  exclude: "*README.md"
  new_doc_ext: md
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - blog-post
- type: directory
  path: _articles
  label: Press
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - press-template
- type: directory
  path: _autotech-events
  label: AutoTech Events
  create: documents
  match: "**/*"
  templates:
  - event-page
- type: document
  path: _data/data.yml
  label: Wunder Data
- type: heading
  label: Settings
- type: document
  path: _data/global.yml
  label: Site Settings
- type: document
  path: FORESTRY-README.md
  label: Welcome - First Steps
  read_only: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: jekyll build
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
