---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: pages
  label: Pages
  create: all
  match: "**/*"
  exclude: "*README.md"
  new_doc_ext: md
- type: directory
  path: wunder_collections/_posts
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: ''
  label: Posts incl. drafts
  create: documents
  match: "{wunder_collections/_posts/*,wunder_collections/_drafts/*}"
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: wunder_collections/_people
  label: People
  create: documents
  match: "**/*"
  templates:
  - speaker
- type: directory
  path: wunder_collections/_articles
  label: Press
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - press-template
- type: directory
  path: wunder_collections/_autotech-events
  label: Mobility Sessions
  create: documents
  match: "**/*"
  templates:
  - event-page
- type: document
  path: _data/weallmove.yml
  label: "#WeAllMove"
- type: heading
  label: Vehicles
- type: directory
  path: wunder_collections/_vehicles
  label: Products
  create: documents
  match: "**/*"
- type: document
  path: _data/vehicles-settings.yml
  label: Vehicles Settings
- type: heading
  label: Custom Settings
- type: document
  path: _data/data.yml
  label: Wunder Data
- type: document
  path: _data/global.yml
  label: Site Settings
- type: document
  path: FORESTRY-README.md
  label: Welcome - First Steps
  read_only: true
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6-node10
  mount_path: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
