---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: document
  path: FORESTRY-README.MD
  label: Welcome - First Steps
  match: "**/*"
  read_only: true
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
