---
new_page_extension: html
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: _data/articles.yml
  label: Articles
  match: "**/*"
- type: directory
  path: _articles
  label: Press
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - press-template
- type: document
  path: _data/data.yml
  label: Wunder Data
- type: document
  path: _data/global.yml
  label: Site Settings
- type: document
  path: FORESTRY-README.md
  label: Welcome - First Steps
  read_only: true
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: pages
  label: Pages
  create: all
  match: "**/*"
  exclude: "*README.md"
  new_doc_ext: md
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: jekyll build
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
