---
label: Global Settings
hide_body: false
fields:
- type: file
  name: logo
  label: Logo
- name: footerlogo
  label: Footerlogo
  type: file
  hidden: false
  default: ''
- name: twitter
  label: Twitter
  type: text
  hidden: false
  default: ''
- name: linkedin
  label: Linkedin
  type: text
  hidden: false
  default: ''
pages:
- _data/global.yml
